version: '3'

volumes:
  db:
    driver: local

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  db:
    environment:
      POSTGRES_USER: "templateuser"
      POSTGRES_DB: "template"
      POSTGRES_PASSWORD: "123321"
    image: postgres:16.3-alpine
    ports:
      - "5432:5432"
    volumes: 
      - db:/var/lib/postgresql/data

  catalog:
    restart: on-failure
    depends_on:
      - db
    build: services/catalog/
    environment:
      SERVER: "0.0.0.0:8080"
      DATABASE_URL: "postgresql://templateuser:123321@db:5432/template"
    ports:
      - "8080:8080"